/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        cream: '#F5F5F0',
        offwhite: '#FAFAFA',
        charcoal: '#2D2D2D',
        softgray: '#E0E0E0',
        mediumgray: '#9E9E9E',
        // Rota Planner design tokens
        rota: {
          'page-bg-from': '#f8fafc',
          'page-bg-via': '#eff6ff',
          'page-bg-to': '#f1f5f9',
          'toolbar-bg': '#ffffff',
          'toolbar-border': '#e5e7eb',
          'day-today-bg-from': '#3b82f6',
          'day-today-bg-to': '#2563eb',
          'day-today-text': '#ffffff',
          'day-other-bg-from': '#f3f4f6',
          'day-other-bg-to': '#e5e7eb',
          'day-other-text': '#1f2937',
          'card-full-border': '#34d399',
          'card-full-bg': 'rgba(167,243,208,0.3)',
          'card-empty-border': '#f87171',
          'card-empty-bg': 'rgba(254,226,226,0.5)',
          'card-partial-border': '#fbbf24',
          'card-partial-bg': 'rgba(254,243,199,0.3)',
          'card-partial-low-border': '#fb923c',
          'card-partial-low-bg': 'rgba(255,237,213,0.3)',
          'badge-full-bg': '#d1fae5',
          'badge-full-text': '#047857',
          'badge-full-border': '#6ee7b7',
          'badge-empty-bg': '#fee2e2',
          'badge-empty-text': '#b91c1c',
          'badge-empty-border': '#fca5a5',
          'badge-partial-bg': '#fef3c7',
          'badge-partial-text': '#b45309',
          'badge-partial-border': '#fcd34d',
          'badge-partial-low-bg': '#ffedd5',
          'badge-partial-low-text': '#c2410c',
          'badge-partial-low-border': '#fdba74',
          'shift-day': '#3b82f6',
          'shift-afternoon': '#6366f1',
          'shift-night': '#64748b',
          'btn-outline-border': '#d1d5db',
          'btn-outline-text': '#2d2d2d',
          'btn-primary-hover-bg': '#eff6ff',
          'btn-primary-hover-text': '#1d4ed8',
          'btn-destructive-border': '#ef4444',
          'btn-destructive-text': '#dc2626',
          'btn-destructive-hover-bg': '#fef2f2',
          'modal-overlay': 'rgba(0,0,0,0.7)',
          'modal-bg': '#ffffff',
          'modal-border': '#e5e7eb',
          'input-border': '#d1d5db',
          'input-focus-ring': 'rgba(59,130,246,0.2)',
          'input-focus-border': '#3b82f6',
          'text-primary': '#2d2d2d',
          'text-muted': '#4b5563',
          'text-muted-light': '#6b7280',
          'alert-error-bg': '#fef2f2',
          'alert-error-border': '#fecaca',
          'alert-error-text': '#b91c1c',
        },
      },
      borderRadius: {
        'xl': '1rem',
        '2xl': '1.5rem',
      },
    },
  },
  plugins: [],
} 