/**
 * Unit tests for CSV Import Helper
 * Tests the aggregation logic for multiple shifts per day
 */

import { 
  parseShunterCSV, 
  dedupeIdenticalEntries, 
  aggregateShiftData,
  timeToSeconds,
  secondsToTime 
} from './csvImportHelper';

describe('Time conversion utilities', () => {
  test('timeToSeconds converts "M:SS" format correctly', () => {
    expect(timeToSeconds('2:31')).toBe(151); // 2*60 + 31
    expect(timeToSeconds('3:45')).toBe(225); // 3*60 + 45
    expect(timeToSeconds('0:05')).toBe(5);
    expect(timeToSeconds('10:00')).toBe(600);
  });

  test('secondsToTime converts back to "M:SS" format', () => {
    expect(secondsToTime(151)).toBe('2:31');
    expect(secondsToTime(225)).toBe('3:45');
    expect(secondsToTime(5)).toBe('0:05');
    expect(secondsToTime(600)).toBe('10:00');
  });

  test('time conversion roundtrip', () => {
    const times = ['1:23', '2:45', '5:00', '0:30', '10:15'];
    times.forEach(time => {
      const seconds = timeToSeconds(time);
      const converted = secondsToTime(seconds);
      expect(converted).toBe(time);
    });
  });
});

describe('CSV Parsing', () => {
  test('parses CSV with multiple shift sections', () => {
    const csvContent = `Report,Shunt Utilisation (Daily)
Generated by,SYSTEM
Generation Time,30-Jan-2026 06:05

Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss),No of full location exceptions
CJ200,Chris Jenkins,38,2:31,2:43,
AG10,Andy Godson,25,1:23,3:01,

Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss),No of full location exceptions
CJ200,Chris Jenkins,38,2:19,2:35,
AG10,Andy Godson,30,1:45,2:50,`;

    const parsed = parseShunterCSV(csvContent);
    
    expect(parsed.length).toBe(4); // 2 users × 2 shifts
    
    // Check Chris Jenkins entries
    const chrisEntries = parsed.filter(e => e.yardSystemId === 'CJ200');
    expect(chrisEntries.length).toBe(2);
    expect(chrisEntries[0].numberOfMoves).toBe(38);
    expect(chrisEntries[1].numberOfMoves).toBe(38);
    expect(chrisEntries[0].avgTimeToCollect).toBe('2:31');
    expect(chrisEntries[1].avgTimeToCollect).toBe('2:19');
  });

  test('skips header repetitions', () => {
    const csvContent = `Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss)
CJ200,Chris Jenkins,38,2:31,2:43,

Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss)
CJ200,Chris Jenkins,38,2:19,2:35,`;

    const parsed = parseShunterCSV(csvContent);
    expect(parsed.length).toBe(2); // Only data rows, headers skipped
  });
});

describe('Deduplication', () => {
  test('does NOT dedupe entries with different times (different shifts)', () => {
    const entries = [
      {
        yardSystemId: 'CJ200',
        fullName: 'Chris Jenkins',
        numberOfMoves: 38,
        avgTimeToCollect: '2:31',
        avgTimeToTravel: '2:43',
        numberOfFullLocations: 0
      },
      {
        yardSystemId: 'CJ200',
        fullName: 'Chris Jenkins',
        numberOfMoves: 38,
        avgTimeToCollect: '2:19', // Different time!
        avgTimeToTravel: '2:35',  // Different time!
        numberOfFullLocations: 0
      }
    ];

    const deduped = dedupeIdenticalEntries(entries);
    expect(deduped.length).toBe(2); // Should keep both (different times = different shifts)
  });

  test('DOES dedupe truly identical entries (YMS export bug)', () => {
    const entries = [
      {
        yardSystemId: 'AW1',
        fullName: 'Andy Wilkinson',
        numberOfMoves: 44,
        avgTimeToCollect: '3:38',
        avgTimeToTravel: '3:31',
        numberOfFullLocations: 0
      },
      {
        yardSystemId: 'AW1',
        fullName: 'Andy Wilkinson ?', // Different name variant
        numberOfMoves: 44,              // But same metrics
        avgTimeToCollect: '3:38',
        avgTimeToTravel: '3:31',
        numberOfFullLocations: 0
      }
    ];

    const deduped = dedupeIdenticalEntries(entries);
    expect(deduped.length).toBe(1); // Should dedupe (identical metrics)
    expect(deduped[0].fullName).toBe('Andy Wilkinson ?'); // Keeps longer name
  });
});

describe('Shift Aggregation - Chris Jenkins Case', () => {
  test('aggregates 2 shifts with different times → 76 total moves', () => {
    const shifts = [
      {
        yardSystemId: 'CJ200',
        fullName: 'Chris Jenkins',
        numberOfMoves: 38,
        avgTimeToCollect: '2:31', // 151 seconds
        avgTimeToTravel: '2:43',   // 163 seconds
        numberOfFullLocations: 0
      },
      {
        yardSystemId: 'CJ200',
        fullName: 'Chris Jenkins',
        numberOfMoves: 38,
        avgTimeToCollect: '2:19', // 139 seconds
        avgTimeToTravel: '2:35',   // 155 seconds
        numberOfFullLocations: 0
      }
    ];

    const aggregated = aggregateShiftData(shifts);
    
    expect(aggregated.length).toBe(1); // One unique shunter
    expect(aggregated[0].yardSystemId).toBe('CJ200');
    expect(aggregated[0].numberOfMoves).toBe(76); // 38 + 38
    expect(aggregated[0].shiftCount).toBe(2);
    
    // Weighted average: (151*38 + 139*38) / 76 = (5738 + 5282) / 76 = 145 seconds = 2:25
    expect(aggregated[0].avgTimeToCollect).toBe('2:25');
    
    // Weighted average: (163*38 + 155*38) / 76 = (6194 + 5890) / 76 = 159 seconds = 2:39
    expect(aggregated[0].avgTimeToTravel).toBe('2:39');
  });

  test('aggregates 3 shifts → correct totals', () => {
    const shifts = [
      {
        yardSystemId: 'TEST1',
        fullName: 'Test User',
        numberOfMoves: 20,
        avgTimeToCollect: '2:00',
        avgTimeToTravel: '3:00',
        numberOfFullLocations: 1
      },
      {
        yardSystemId: 'TEST1',
        fullName: 'Test User',
        numberOfMoves: 30,
        avgTimeToCollect: '2:30',
        avgTimeToTravel: '3:30',
        numberOfFullLocations: 2
      },
      {
        yardSystemId: 'TEST1',
        fullName: 'Test User',
        numberOfMoves: 50,
        avgTimeToCollect: '3:00',
        avgTimeToTravel: '4:00',
        numberOfFullLocations: 0
      }
    ];

    const aggregated = aggregateShiftData(shifts);
    
    expect(aggregated.length).toBe(1);
    expect(aggregated[0].numberOfMoves).toBe(100); // 20+30+50
    expect(aggregated[0].shiftCount).toBe(3);
    expect(aggregated[0].numberOfFullLocations).toBe(3); // 1+2+0
    
    // Weighted avg collect: (120*20 + 150*30 + 180*50) / 100 = (2400+4500+9000) / 100 = 159s = 2:39
    expect(aggregated[0].avgTimeToCollect).toBe('2:39');
    
    // Weighted avg travel: (180*20 + 210*30 + 240*50) / 100 = (3600+6300+12000) / 100 = 219s = 3:39
    expect(aggregated[0].avgTimeToTravel).toBe('3:39');
  });

  test('handles single shift (no aggregation needed)', () => {
    const shifts = [
      {
        yardSystemId: 'SINGLE1',
        fullName: 'Single Shift User',
        numberOfMoves: 45,
        avgTimeToCollect: '2:15',
        avgTimeToTravel: '3:20',
        numberOfFullLocations: 0
      }
    ];

    const aggregated = aggregateShiftData(shifts);
    
    expect(aggregated.length).toBe(1);
    expect(aggregated[0].numberOfMoves).toBe(45);
    expect(aggregated[0].shiftCount).toBe(1);
    expect(aggregated[0].avgTimeToCollect).toBe('2:15');
    expect(aggregated[0].avgTimeToTravel).toBe('3:20');
  });

  test('aggregates multiple users independently', () => {
    const shifts = [
      { yardSystemId: 'USER1', fullName: 'User One', numberOfMoves: 20, avgTimeToCollect: '2:00', avgTimeToTravel: '3:00', numberOfFullLocations: 0 },
      { yardSystemId: 'USER2', fullName: 'User Two', numberOfMoves: 30, avgTimeToCollect: '2:30', avgTimeToTravel: '3:30', numberOfFullLocations: 0 },
      { yardSystemId: 'USER1', fullName: 'User One', numberOfMoves: 25, avgTimeToCollect: '2:10', avgTimeToTravel: '3:10', numberOfFullLocations: 0 },
      { yardSystemId: 'USER2', fullName: 'User Two', numberOfMoves: 35, avgTimeToCollect: '2:40', avgTimeToTravel: '3:40', numberOfFullLocations: 0 },
    ];

    const aggregated = aggregateShiftData(shifts);
    
    expect(aggregated.length).toBe(2); // Two unique users
    
    const user1 = aggregated.find(u => u.yardSystemId === 'USER1');
    const user2 = aggregated.find(u => u.yardSystemId === 'USER2');
    
    expect(user1.numberOfMoves).toBe(45); // 20+25
    expect(user1.shiftCount).toBe(2);
    
    expect(user2.numberOfMoves).toBe(65); // 30+35
    expect(user2.shiftCount).toBe(2);
  });
});

describe('Full Integration Test - Chris Jenkins from CSV', () => {
  test('full pipeline: parse → dedupe → aggregate', () => {
    // This is the actual CSV content from Shunters (1).csv for Chris Jenkins
    const csvContent = `Report,Shunt Utilisation (Daily)
Generated by,SYSTEM
Generation Time,30-Jan-2026 06:05

Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss),No of full location exceptions

Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss),No of full location exceptions
CJ200,Chris Jenkins,38,2:31,2:43,

Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss),No of full location exceptions
CJ200,Chris Jenkins,38,2:19,2:35,`;

    // Step 1: Parse CSV
    const parsed = parseShunterCSV(csvContent);
    expect(parsed.length).toBe(2); // 2 shift entries for Chris
    
    // Step 2: Dedupe (should NOT dedupe - different times)
    const deduped = dedupeIdenticalEntries(parsed);
    expect(deduped.length).toBe(2); // Still 2 entries
    
    // Step 3: Aggregate
    const aggregated = aggregateShiftData(deduped);
    expect(aggregated.length).toBe(1); // 1 unique shunter
    expect(aggregated[0].yardSystemId).toBe('CJ200');
    expect(aggregated[0].numberOfMoves).toBe(76); // 38 + 38 = 76 ✅
    expect(aggregated[0].shiftCount).toBe(2);
    
    console.log('✅ Full integration test passed: Chris Jenkins correctly aggregated to 76 moves');
  });
});

describe('Edge Cases', () => {
  test('handles zero moves gracefully', () => {
    const shifts = [
      {
        yardSystemId: 'ZERO1',
        fullName: 'Zero User',
        numberOfMoves: 0,
        avgTimeToCollect: '0:00',
        avgTimeToTravel: '0:00',
        numberOfFullLocations: 0
      }
    ];

    const aggregated = aggregateShiftData(shifts);
    expect(aggregated[0].numberOfMoves).toBe(0);
    expect(aggregated[0].avgTimeToCollect).toBe('0:00');
  });

  test('handles empty array', () => {
    const aggregated = aggregateShiftData([]);
    expect(aggregated.length).toBe(0);
  });

  test('uppercase conversion for yard IDs', () => {
    const csvContent = `Shunter user id,Full name,No of moves,Average time to collect (mm:ss),Average time to travel (mm:ss)
cj200,Chris Jenkins,38,2:31,2:43,`;

    const parsed = parseShunterCSV(csvContent);
    expect(parsed[0].yardSystemId).toBe('CJ200'); // Should be uppercase
  });
});
